### 다음 두 벡터에 대해 모두 직교하는 단위벡터를 찾아라.

In [1]:
import numpy as np

In [2]:
a = np.array([[1], [1], [0]])
a

array([[1],
       [1],
       [0]])

In [4]:
a.shape

(3, 1)

In [6]:
b = np.array([[1], [0], [0]])
b

array([[1],
       [0],
       [0]])

In [8]:
a.T @ b

array([[1]])

In [9]:
b.T @ a

array([[1]])

In [ ]:
a.T @ x = 0
b.T @ x = 0