In [1]:
import numpy as np

In [3]:
A = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 4]])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [4]:
Ainv = np.linalg.inv(A)
Ainv

array([[1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

## 역행렬과 선형 연립방정식의 해

In [5]:
b = np.array([[1], [2], [4]])
b

array([[1],
       [2],
       [4]])

In [10]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [9]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [11]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

/home/ktnet/Git/data-science-school/venv/lib/python3.5/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.],
       [1.],
       [1.]])

## 보스턴 집값구하기 문제

In [12]:
from sklearn.datasets import load_boston
boston = load_boston()

In [13]:
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 범죄율(CRIM), 공기 오염도(NOX), 방의 개수(RM), 오래된 정도(AGE)
b = y[:4]

In [22]:
x, resid, rank, s = np.linalg.lstsq(A, b)

/home/ktnet/Git/data-science-school/venv/lib/python3.5/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [23]:
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

## 최소자승문제

In [24]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [27]:
x, resid, rank, s = np.linalg.lstsq(X, y)

/home/ktnet/Git/data-science-school/venv/lib/python3.5/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [28]:
x

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])